### ISSUE TITLE
IndexError: list assignment index out of range

### ISSUE THREAD

**Issue by hafidmermouri** [memosstilvi/simhash#1]
hello
if i initiate the constructor with 64 bit parameter, i get this error
`hash = simhash2.simhash(y.encode('utf-8'), 64)`

any work around ?

**Comment by memosstilvi** [comment]
@hafidmermouri 
The reason is that I am using `md5` that produces a 128 bit hash value.
As you can see in my comments [here](https://github.com/memosstilvi/simhash/blob/master/simhash.py#L82) you need to use a different hash function if you want to modify the length of the hash.
